//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LateOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventarioFisico
    {
        public int invf_id { get; set; }
        public int prod_Id { get; set; }
        public int invf_total { get; set; }
        public Nullable<System.DateTime> invf_FechaInventario { get; set; }
        public int invf_UsuarioCrea { get; set; }
        public System.DateTime invf_FechaCrea { get; set; }
        public Nullable<int> invf_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> invf_FechaModifica { get; set; }
    
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
        public virtual tbProducto tbProducto { get; set; }
    }
}
