//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LateOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCarrito
    {
        public int car_Id { get; set; }
        public Nullable<int> clte_Id { get; set; }
        public Nullable<int> prod_Id { get; set; }
        public Nullable<System.DateTime> car_FechaOrden { get; set; }
        public Nullable<int> car_Cantidad { get; set; }
    
        public virtual tbCliente tbCliente { get; set; }
        public virtual tbProducto tbProducto { get; set; }
    }
}
