//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LateOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbClienteDireccion
    {
        public int clted_Id { get; set; }
        public string clted_Descripcion { get; set; }
        public int clte_Id { get; set; }
        public int ciu_Id { get; set; }
        public int clted_UsuarioCrea { get; set; }
        public System.DateTime clted_FechaCrea { get; set; }
        public Nullable<int> clted_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> clted_FechaModifica { get; set; }
    
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
        public virtual tbCiudad tbCiudad { get; set; }
        public virtual tbCliente tbCliente { get; set; }
    }
}
