//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LateOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDevolucionDetalle
    {
        public int devd_Id { get; set; }
        public int dev_Id { get; set; }
        public int prod_Id { get; set; }
        public decimal prod_Precio { get; set; }
        public int devd_Cantidad { get; set; }
        public Nullable<decimal> devd_Impuesto { get; set; }
        public Nullable<decimal> devd_Descuento { get; set; }
        public int devd_UsuarioCrea { get; set; }
        public System.DateTime devd_FechaCrea { get; set; }
        public Nullable<int> devd_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> devd_FechaModifica { get; set; }
    
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
        public virtual tbDevolucion tbDevolucion { get; set; }
    }
}
