//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LateOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEmpleado
    {
        public int emp_Id { get; set; }
        public string emp_Identidad { get; set; }
        public string emp_Nombres { get; set; }
        public string emp_Apellidos { get; set; }
        public System.DateTime emp_FechaNacimiento { get; set; }
        public string emp_Sexo { get; set; }
        public string emp_CorreoElectronico { get; set; }
        public string emp_Telefono { get; set; }
        public System.DateTime emp_FechaIngreso { get; set; }
        public Nullable<bool> emp_EsActivo { get; set; }
        public int empc_id { get; set; }
        public int usu_Id { get; set; }
        public int emp_UsuarioCrea { get; set; }
        public System.DateTime emp_FechaCrea { get; set; }
        public Nullable<int> emp_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> emp_FechaModifica { get; set; }
    
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
        public virtual tbUsuarios tbUsuarios2 { get; set; }
        public virtual tbEmpleadoCargo tbEmpleadoCargo { get; set; }
    }
}
