//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LateOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEntrada
    {
        public int ent_Id { get; set; }
        public int prod_Id { get; set; }
        public int ent_Existencia { get; set; }
        public int ent_Cantidad { get; set; }
        public System.DateTime ent_FechaEntrada { get; set; }
        public int ent_UsuarioCrea { get; set; }
        public System.DateTime ent_FechaCrea { get; set; }
        public Nullable<int> ent_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> ent_FechaModifica { get; set; }
    
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
        public virtual tbProducto tbProducto { get; set; }
    }
}
