//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LateOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbListadoPrecio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbListadoPrecio()
        {
            this.tbListadoPrecioDetalle = new HashSet<tbListadoPrecioDetalle>();
        }
    
        public int lip_Id { get; set; }
        public string lip_Descripcion { get; set; }
        public int lip_Prioridad { get; set; }
        public bool lip_EsActivo { get; set; }
        public System.DateTime lip_FechaInicio { get; set; }
        public System.DateTime lip_FechaFin { get; set; }
        public int lip_UsuarioCrea { get; set; }
        public System.DateTime lip_FechaCrea { get; set; }
        public Nullable<int> lip_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> lip_FechaModifica { get; set; }
    
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbListadoPrecioDetalle> tbListadoPrecioDetalle { get; set; }
    }
}
