//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LateOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPais
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbPais()
        {
            this.tbCiudad = new HashSet<tbCiudad>();
        }
    
        public int pais_Id { get; set; }
        public string pais_Descripcion { get; set; }
        public int pais_UsuarioCrea { get; set; }
        public System.DateTime pais_FechaCrea { get; set; }
        public Nullable<int> pais_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> pais_FechaModifica { get; set; }
    
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCiudad> tbCiudad { get; set; }
    }
}
