//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LateOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProductoImagen
    {
        public int proi_Id { get; set; }
        public Nullable<int> prod_Id { get; set; }
        public Nullable<int> proi_UsuarioCrea { get; set; }
        public Nullable<System.DateTime> proi_FechaCrea { get; set; }
        public Nullable<int> proi_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> proi_FechaModifica { get; set; }
        public string proi_imagen { get; set; }
    
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
        public virtual tbProducto tbProducto { get; set; }
    }
}
