//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LateOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTransaccionDetalle
    {
        public int trad_Id { get; set; }
        public string trad_Descripcion { get; set; }
        public System.DateTime trad_Fecha { get; set; }
        public int fact_Id { get; set; }
        public int trad_UsuarioCrea { get; set; }
        public System.DateTime trad_FechaCrea { get; set; }
        public Nullable<int> trad_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> trad_FechaModifica { get; set; }
        public int estt_Id { get; set; }
    
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
        public virtual tbFactura tbFactura { get; set; }
        public virtual tbEstadoTransaccion tbEstadoTransaccion { get; set; }
    }
}
