//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LateOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario_Rol
    {
        public int id { get; set; }
        public Nullable<int> usu_Id { get; set; }
        public Nullable<int> id_Rol { get; set; }
    
        public virtual tbRol tbRol { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
    }
}
