//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LateOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Usuarios
    {
        public int usu_Id { get; set; }
        public string usu_NombreUsuario { get; set; }
        public string clte_Nombre { get; set; }
        public string clte_Apellido { get; set; }
        public string clte_Correo { get; set; }
        public byte[] usu_Password { get; set; }
        public string usu_Token { get; set; }
        public Nullable<int> clte_Id { get; set; }
        public string clte_Sexo { get; set; }
        public string clte_Telefono { get; set; }
    }
}
